### ISSUE TITLE
About  train.py !!

### ISSUE THREAD

**Issue by Z-Z-J** [Shimingyi/MotioNet#13]
# wild videos
python train.py -n wild -d 1 --kernel_size 5,3,1 --stride 3,1,1 --dilation 1,1,1 --channel 1024 --confidence 1 --translation 1 --contact 1 --loss_term 1101

First，I noticed that  config.trainer.data  always  is  "gt" 。This means  only use  “./data/data_h36m.npz " to train 。
Second, Can you provide './data/data_2d_h36m_cpn_ft_h36m_dbb.npz' and './data/data_2d_h36m_detectron_ft_h36m.npz'  ??

**Comment by Shimingyi** [comment]
I will suggest to train our model on ```gt``` settings, because we simulate the noise distribution which is wild video, it can make our noises more realistic. If you train it on fine-tuned detecton or cpn, the noise is just from human3.6m.  And also, the training with ```gt``` will get best performance, so we only realease the these pre-train models and configration based on gt-training. 

If you still want to use other dataset or 2d detection to train the model, you can refer [VideoPose](https://github.com/facebookresearch/VideoPose3D) to get their data, and then put them into _./data_ folder, run command with ```--data cpn``` or ```--data detectron```. The hyper parameters and model structure need to be updated to get similar performance(still worse than gt).

**Comment by Z-Z-J** [comment]
Thank you for such a quick reply !! Can you add me to QQ ?  I am a student of Beijing University of Posts and Telecommunications ! My English is relatively poor, so I hope I can communicate with you in Chinese.After you add my QQ, I will send emails to ask you questions, without disturbing your normal life. My QQ : 1546375589 。If it is inconvenient, I will continue to ask you questions on github。No matter what, thank you!!!

**Comment by snitchjinx** [comment]
Hello Mingyi! Shall we also add QQ friends? My QQ is 908982572. I have a few questions about the project and really would like to discuss them with you. Thank you!
