### ISSUE TITLE
Read the output of openpose on wild videos 

### ISSUE THREAD

**Issue by italosalgado14** [Shimingyi/MotioNet#40]
Hi there. Thanks for the code. I am trying to test it on videos that I have recorded, but I run into the following problem reading the output of openpose.
I use:
>> ./build/examples/openpose/openpose.bin --video /home/laila/Nexar/openpose/examples/media/nombre_final.mp4 --write_json /home/laila/Nexar/openpose/out_openpose  --display 0 --render_pose 0
And:
>> python evaluate.py -r ./checkpoints/wild_gt_tcc.pth -i /home/laila/Nexar/openpose/out_openpose/ -o /home/laila/Nexar/MotioNet/output/testvid

But my output is:
(env) laila@laila:~/Nexar/MotioNet$ python evaluate.py -r ./checkpoints/wild_gt_tcc.pth -i /home/laila/Nexar/openpose/out_openpose/ -o /home/laila/Nexar/MotioNet/output/testvid
Building the network
Traceback (most recent call last):
  File "/home/laila/Nexar/MotioNet/evaluate.py", line 148, in <module>
    main(config, args, output_folder)
  File "/home/laila/Nexar/MotioNet/evaluate.py", line 124, in main
    export(args.input)
  File "/home/laila/Nexar/MotioNet/evaluate.py", line 78, in export
    files = util.make_dataset([pose_folder], phase='json', data_split=1, sort=True, sort_index=1)
  File "/home/laila/Nexar/MotioNet/utils/util.py", line 28, in make_dataset
    _images.sort(key=lambda x: int(x.split('/')[-1].split('.')[0].split('_')[sort_index]))
  File "/home/laila/Nexar/MotioNet/utils/util.py", line 28, in <lambda>
    _images.sort(key=lambda x: int(x.split('/')[-1].split('.')[0].split('_')[sort_index]))
ValueError: invalid literal for int() with base 10: 'final'
In advance thanks for the help! =)

**Comment by Shimingyi** [comment]
Hi @italosalgado14 , the problem happens when sorting the images by the filename. In line 18:
```
_images.sort(key=lambda x: int(x.split('/')[-1].split('.')[0].split('_')[sort_index]))
```
Firstly, the image file path will be split two times by **'/'** and **'.'** to get the filename, like _final_000_, and then take the index part by splitting **'_'**. In my function, I use the variable **sort_index** to control where we take the number part, if the filename is _final_000_, then it should be 1, or if the filename is _final_video_000_, this variable should be 2.

This variable can be modified in this [line](https://github.com/Shimingyi/MotioNet/blob/master/evaluate.py#L76). You can check it.
