### ISSUE TITLE
bone2skeleton conversion

### ISSUE THREAD

**Issue by snitchjinx** [Shimingyi/MotioNet#8]
Hello, thanks for sharing this nice work!

I have a question regarding the bone to skeleton conversion function in ./models/model.py
It seems the joints are shifted from the pelvis joint by offsets of bone lengths, but why is there no horizontal offsets for RKnee, RAnkle, LKnee, and LAnkle. I was expecting something like:

skel_in[:, 2, 0] = -unnorm_bones[:, 0, 0]
skel_in[:, 5, 0] = unnorm_bones[:, 0, 0]
skel_in[:, 3, 0] = -unnorm_bones[:, 0, 0]
skel_in[:, 6, 0] = unnorm_bones[:, 0, 0]

Thanks in advance for consideration!

**Comment by Shimingyi** [comment]
Hello! A good question! 

We use this function to convert the bone length to T-skeleton, in here we haven't apply the horizontal offsets to this T-skeleton because we found this kind of setting will be more similar to various character model, so it's better for skinning and other processes. 

<img width="800" alt="20200910150611" src="https://user-images.githubusercontent.com/7709951/92692760-355a7580-f377-11ea-9bf9-cb6f2ca1d75a.png">

But because we only apply positional loss directly in our training, so the model can also converage if you use different setting.

**Comment by snitchjinx** [comment]
Thanks!

**Comment by longbowzhang** [comment]
Hi @Shimingyi 
I am also curious about the bones2skel function in model.py.
I guess this function constructs the skeleton in terms of _relative_ positions based on the following two oberservations.
- `skel_in[:, 2, 1] = -unnorm_bones[:, 0, 1]` means the position of RKnee is unnorm_bones[:, 0, 1] below (i.e., negative y-axis) its parent joint RHip, and there is no horizontal offset w.r.t RHip.
- as shown in the function of _transforms_global_ in model_zoo.py, the positions (i.e., the constructed skeleton) is first used to build _locals_.

But I would like to double check with you about bones2skel whether it expresses the t-pose skeleton in terms of _relative_ positions or _absolute_ positions.

Many thanks.

**Comment by Shimingyi** [comment]
Hi@longbowzhang ,

You are right, it's not the absolute position in a 3d space. Each value is the relative position compared to its parent joint. 
This code can help you to undersantd it better: [get_skel](https://github.com/rubenvillegas/cvpr2018nkn/blob/98ffeec82f8ad57bbaa81a0c6eb76283462bb97b/datasets/preprocess.py#L21)

Best,
Mingyi
